// Generated by gencpp from file ecu_msgs/GenerateFault.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_GENERATEFAULT_H
#define ECU_MSGS_MESSAGE_GENERATEFAULT_H

#include <ros/service_traits.h>


#include <ecu_msgs/GenerateFaultRequest.h>
#include <ecu_msgs/GenerateFaultResponse.h>


namespace ecu_msgs
{

struct GenerateFault
{

typedef GenerateFaultRequest Request;
typedef GenerateFaultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateFault
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::GenerateFault > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::ecu_msgs::GenerateFault&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::GenerateFault > {
  static const char* value()
  {
    return "ecu_msgs/GenerateFault";
  }

  static const char* value(const ::ecu_msgs::GenerateFault&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::GenerateFaultRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::GenerateFault > 
template<>
struct MD5Sum< ::ecu_msgs::GenerateFaultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::GenerateFault >::value();
  }
  static const char* value(const ::ecu_msgs::GenerateFaultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::GenerateFaultRequest> should match 
// service_traits::DataType< ::ecu_msgs::GenerateFault > 
template<>
struct DataType< ::ecu_msgs::GenerateFaultRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::GenerateFault >::value();
  }
  static const char* value(const ::ecu_msgs::GenerateFaultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::GenerateFaultResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::GenerateFault > 
template<>
struct MD5Sum< ::ecu_msgs::GenerateFaultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::GenerateFault >::value();
  }
  static const char* value(const ::ecu_msgs::GenerateFaultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::GenerateFaultResponse> should match 
// service_traits::DataType< ::ecu_msgs::GenerateFault > 
template<>
struct DataType< ::ecu_msgs::GenerateFaultResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::GenerateFault >::value();
  }
  static const char* value(const ::ecu_msgs::GenerateFaultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_GENERATEFAULT_H
