// Generated by gencpp from file ecu_msgs/SetActiveOneRequest.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETACTIVEONEREQUEST_H
#define ECU_MSGS_MESSAGE_SETACTIVEONEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ecu_msgs
{
template <class ContainerAllocator>
struct SetActiveOneRequest_
{
  typedef SetActiveOneRequest_<ContainerAllocator> Type;

  SetActiveOneRequest_()
    : state(false)
    , index(0)  {
    }
  SetActiveOneRequest_(const ContainerAllocator& _alloc)
    : state(false)
    , index(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef int64_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetActiveOneRequest_

typedef ::ecu_msgs::SetActiveOneRequest_<std::allocator<void> > SetActiveOneRequest;

typedef boost::shared_ptr< ::ecu_msgs::SetActiveOneRequest > SetActiveOneRequestPtr;
typedef boost::shared_ptr< ::ecu_msgs::SetActiveOneRequest const> SetActiveOneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ecu_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ecu_msgs': ['/home/user/milrem/src/ecu_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6ac0aeb0941f5513fea6f06f1e5d3d6";
  }

  static const char* value(const ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6ac0aeb0941f551ULL;
  static const uint64_t static_value2 = 0x3fea6f06f1e5d3d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecu_msgs/SetActiveOneRequest";
  }

  static const char* value(const ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
"int64 index\n"
;
  }

  static const char* value(const ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetActiveOneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ecu_msgs::SetActiveOneRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "index: ";
    Printer<int64_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETACTIVEONEREQUEST_H
