// Generated by gencpp from file ecu_msgs/SetBatteryCapacityRequest.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETBATTERYCAPACITYREQUEST_H
#define ECU_MSGS_MESSAGE_SETBATTERYCAPACITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ecu_msgs
{
template <class ContainerAllocator>
struct SetBatteryCapacityRequest_
{
  typedef SetBatteryCapacityRequest_<ContainerAllocator> Type;

  SetBatteryCapacityRequest_()
    : capacity(0.0)  {
    }
  SetBatteryCapacityRequest_(const ContainerAllocator& _alloc)
    : capacity(0.0)  {
  (void)_alloc;
    }



   typedef double _capacity_type;
  _capacity_type capacity;





  typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBatteryCapacityRequest_

typedef ::ecu_msgs::SetBatteryCapacityRequest_<std::allocator<void> > SetBatteryCapacityRequest;

typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityRequest > SetBatteryCapacityRequestPtr;
typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityRequest const> SetBatteryCapacityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ecu_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ecu_msgs': ['/home/user/milrem/src/ecu_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6f1e9e76186954ea722a13aaffa39e8";
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6f1e9e76186954eULL;
  static const uint64_t static_value2 = 0xa722a13aaffa39e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecu_msgs/SetBatteryCapacityRequest";
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 capacity\n"
;
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.capacity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBatteryCapacityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ecu_msgs::SetBatteryCapacityRequest_<ContainerAllocator>& v)
  {
    s << indent << "capacity: ";
    Printer<double>::stream(s, indent + "  ", v.capacity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETBATTERYCAPACITYREQUEST_H
