// Generated by gencpp from file ecu_msgs/SetBatteryRate.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETBATTERYRATE_H
#define ECU_MSGS_MESSAGE_SETBATTERYRATE_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetBatteryRateRequest.h>
#include <ecu_msgs/SetBatteryRateResponse.h>


namespace ecu_msgs
{

struct SetBatteryRate
{

typedef SetBatteryRateRequest Request;
typedef SetBatteryRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBatteryRate
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetBatteryRate > {
  static const char* value()
  {
    return "d62957aebeb7df19acf301078ca1beab";
  }

  static const char* value(const ::ecu_msgs::SetBatteryRate&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetBatteryRate > {
  static const char* value()
  {
    return "ecu_msgs/SetBatteryRate";
  }

  static const char* value(const ::ecu_msgs::SetBatteryRate&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetBatteryRateRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetBatteryRate > 
template<>
struct MD5Sum< ::ecu_msgs::SetBatteryRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetBatteryRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetBatteryRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetBatteryRateRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetBatteryRate > 
template<>
struct DataType< ::ecu_msgs::SetBatteryRateRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetBatteryRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetBatteryRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetBatteryRateResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetBatteryRate > 
template<>
struct MD5Sum< ::ecu_msgs::SetBatteryRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetBatteryRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetBatteryRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetBatteryRateResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetBatteryRate > 
template<>
struct DataType< ::ecu_msgs::SetBatteryRateResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetBatteryRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetBatteryRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETBATTERYRATE_H
