// Generated by gencpp from file ecu_msgs/SetBatteryCapacityResponse.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETBATTERYCAPACITYRESPONSE_H
#define ECU_MSGS_MESSAGE_SETBATTERYCAPACITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ecu_msgs
{
template <class ContainerAllocator>
struct SetBatteryCapacityResponse_
{
  typedef SetBatteryCapacityResponse_<ContainerAllocator> Type;

  SetBatteryCapacityResponse_()
    : capacity_set(0.0)
    , message()  {
    }
  SetBatteryCapacityResponse_(const ContainerAllocator& _alloc)
    : capacity_set(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef double _capacity_set_type;
  _capacity_set_type capacity_set;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetBatteryCapacityResponse_

typedef ::ecu_msgs::SetBatteryCapacityResponse_<std::allocator<void> > SetBatteryCapacityResponse;

typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityResponse > SetBatteryCapacityResponsePtr;
typedef boost::shared_ptr< ::ecu_msgs::SetBatteryCapacityResponse const> SetBatteryCapacityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ecu_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ecu_msgs': ['/home/user/milrem/src/ecu_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e57c7c66514140c709ea048d183ee86";
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e57c7c66514140cULL;
  static const uint64_t static_value2 = 0x709ea048d183ee86ULL;
};

template<class ContainerAllocator>
struct DataType< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecu_msgs/SetBatteryCapacityResponse";
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 capacity_set\n"
"string message\n"
;
  }

  static const char* value(const ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.capacity_set);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBatteryCapacityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ecu_msgs::SetBatteryCapacityResponse_<ContainerAllocator>& v)
  {
    s << indent << "capacity_set: ";
    Printer<double>::stream(s, indent + "  ", v.capacity_set);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETBATTERYCAPACITYRESPONSE_H
