// Generated by gencpp from file ecu_msgs/SetCmdVelTimeout.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETCMDVELTIMEOUT_H
#define ECU_MSGS_MESSAGE_SETCMDVELTIMEOUT_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetCmdVelTimeoutRequest.h>
#include <ecu_msgs/SetCmdVelTimeoutResponse.h>


namespace ecu_msgs
{

struct SetCmdVelTimeout
{

typedef SetCmdVelTimeoutRequest Request;
typedef SetCmdVelTimeoutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCmdVelTimeout
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetCmdVelTimeout > {
  static const char* value()
  {
    return "a930c3e567f6e537d684459fe0a47d84";
  }

  static const char* value(const ::ecu_msgs::SetCmdVelTimeout&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetCmdVelTimeout > {
  static const char* value()
  {
    return "ecu_msgs/SetCmdVelTimeout";
  }

  static const char* value(const ::ecu_msgs::SetCmdVelTimeout&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetCmdVelTimeoutRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetCmdVelTimeout > 
template<>
struct MD5Sum< ::ecu_msgs::SetCmdVelTimeoutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetCmdVelTimeout >::value();
  }
  static const char* value(const ::ecu_msgs::SetCmdVelTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetCmdVelTimeoutRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetCmdVelTimeout > 
template<>
struct DataType< ::ecu_msgs::SetCmdVelTimeoutRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetCmdVelTimeout >::value();
  }
  static const char* value(const ::ecu_msgs::SetCmdVelTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetCmdVelTimeoutResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetCmdVelTimeout > 
template<>
struct MD5Sum< ::ecu_msgs::SetCmdVelTimeoutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetCmdVelTimeout >::value();
  }
  static const char* value(const ::ecu_msgs::SetCmdVelTimeoutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetCmdVelTimeoutResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetCmdVelTimeout > 
template<>
struct DataType< ::ecu_msgs::SetCmdVelTimeoutResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetCmdVelTimeout >::value();
  }
  static const char* value(const ::ecu_msgs::SetCmdVelTimeoutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETCMDVELTIMEOUT_H
