// Generated by gencpp from file ecu_msgs/SetFloat.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETFLOAT_H
#define ECU_MSGS_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetFloatRequest.h>
#include <ecu_msgs/SetFloatResponse.h>


namespace ecu_msgs
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetFloat > {
  static const char* value()
  {
    return "38182d080345fe1cb5b538699e1a64ec";
  }

  static const char* value(const ::ecu_msgs::SetFloat&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetFloat > {
  static const char* value()
  {
    return "ecu_msgs/SetFloat";
  }

  static const char* value(const ::ecu_msgs::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetFloatRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetFloat > 
template<>
struct MD5Sum< ::ecu_msgs::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetFloat >::value();
  }
  static const char* value(const ::ecu_msgs::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetFloatRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetFloat > 
template<>
struct DataType< ::ecu_msgs::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetFloat >::value();
  }
  static const char* value(const ::ecu_msgs::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetFloatResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetFloat > 
template<>
struct MD5Sum< ::ecu_msgs::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetFloat >::value();
  }
  static const char* value(const ::ecu_msgs::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetFloatResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetFloat > 
template<>
struct DataType< ::ecu_msgs::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetFloat >::value();
  }
  static const char* value(const ::ecu_msgs::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETFLOAT_H
