// Generated by gencpp from file ecu_msgs/SetLoopRate.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETLOOPRATE_H
#define ECU_MSGS_MESSAGE_SETLOOPRATE_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetLoopRateRequest.h>
#include <ecu_msgs/SetLoopRateResponse.h>


namespace ecu_msgs
{

struct SetLoopRate
{

typedef SetLoopRateRequest Request;
typedef SetLoopRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLoopRate
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetLoopRate > {
  static const char* value()
  {
    return "e70f420dd3814e680a1961a45937fb63";
  }

  static const char* value(const ::ecu_msgs::SetLoopRate&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetLoopRate > {
  static const char* value()
  {
    return "ecu_msgs/SetLoopRate";
  }

  static const char* value(const ::ecu_msgs::SetLoopRate&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetLoopRateRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetLoopRate > 
template<>
struct MD5Sum< ::ecu_msgs::SetLoopRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetLoopRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetLoopRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetLoopRateRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetLoopRate > 
template<>
struct DataType< ::ecu_msgs::SetLoopRateRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetLoopRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetLoopRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetLoopRateResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetLoopRate > 
template<>
struct MD5Sum< ::ecu_msgs::SetLoopRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetLoopRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetLoopRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetLoopRateResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetLoopRate > 
template<>
struct DataType< ::ecu_msgs::SetLoopRateResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetLoopRate >::value();
  }
  static const char* value(const ::ecu_msgs::SetLoopRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETLOOPRATE_H
