// Generated by gencpp from file ecu_msgs/SetNoise.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETNOISE_H
#define ECU_MSGS_MESSAGE_SETNOISE_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetNoiseRequest.h>
#include <ecu_msgs/SetNoiseResponse.h>


namespace ecu_msgs
{

struct SetNoise
{

typedef SetNoiseRequest Request;
typedef SetNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNoise
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetNoise > {
  static const char* value()
  {
    return "df0f4993ee2769576c79259787020080";
  }

  static const char* value(const ::ecu_msgs::SetNoise&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetNoise > {
  static const char* value()
  {
    return "ecu_msgs/SetNoise";
  }

  static const char* value(const ::ecu_msgs::SetNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetNoiseRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetNoise > 
template<>
struct MD5Sum< ::ecu_msgs::SetNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetNoise >::value();
  }
  static const char* value(const ::ecu_msgs::SetNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetNoiseRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetNoise > 
template<>
struct DataType< ::ecu_msgs::SetNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetNoise >::value();
  }
  static const char* value(const ::ecu_msgs::SetNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetNoiseResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetNoise > 
template<>
struct MD5Sum< ::ecu_msgs::SetNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetNoise >::value();
  }
  static const char* value(const ::ecu_msgs::SetNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetNoiseResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetNoise > 
template<>
struct DataType< ::ecu_msgs::SetNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetNoise >::value();
  }
  static const char* value(const ::ecu_msgs::SetNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETNOISE_H
