// Generated by gencpp from file ecu_msgs/SetNoiseRequest.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETNOISEREQUEST_H
#define ECU_MSGS_MESSAGE_SETNOISEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ecu_msgs
{
template <class ContainerAllocator>
struct SetNoiseRequest_
{
  typedef SetNoiseRequest_<ContainerAllocator> Type;

  SetNoiseRequest_()
    : position(0.0)
    , angle(0.0)
    , velocity(0.0)  {
    }
  SetNoiseRequest_(const ContainerAllocator& _alloc)
    : position(0.0)
    , angle(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _position_type;
  _position_type position;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetNoiseRequest_

typedef ::ecu_msgs::SetNoiseRequest_<std::allocator<void> > SetNoiseRequest;

typedef boost::shared_ptr< ::ecu_msgs::SetNoiseRequest > SetNoiseRequestPtr;
typedef boost::shared_ptr< ::ecu_msgs::SetNoiseRequest const> SetNoiseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ecu_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ecu_msgs': ['/home/user/milrem/src/ecu_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32f049d3cc4e9f830a1b9a92fb86efe9";
  }

  static const char* value(const ::ecu_msgs::SetNoiseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32f049d3cc4e9f83ULL;
  static const uint64_t static_value2 = 0x0a1b9a92fb86efe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecu_msgs/SetNoiseRequest";
  }

  static const char* value(const ::ecu_msgs::SetNoiseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position\n"
"float64 angle\n"
"float64 velocity\n"
;
  }

  static const char* value(const ::ecu_msgs::SetNoiseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNoiseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ecu_msgs::SetNoiseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ecu_msgs::SetNoiseRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETNOISEREQUEST_H
