// Generated by gencpp from file ecu_msgs/SetSave.msg
// DO NOT EDIT!


#ifndef ECU_MSGS_MESSAGE_SETSAVE_H
#define ECU_MSGS_MESSAGE_SETSAVE_H

#include <ros/service_traits.h>


#include <ecu_msgs/SetSaveRequest.h>
#include <ecu_msgs/SetSaveResponse.h>


namespace ecu_msgs
{

struct SetSave
{

typedef SetSaveRequest Request;
typedef SetSaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSave
} // namespace ecu_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecu_msgs::SetSave > {
  static const char* value()
  {
    return "4de3d9cc11cc57aecc1e3b15cb59ccfc";
  }

  static const char* value(const ::ecu_msgs::SetSave&) { return value(); }
};

template<>
struct DataType< ::ecu_msgs::SetSave > {
  static const char* value()
  {
    return "ecu_msgs/SetSave";
  }

  static const char* value(const ::ecu_msgs::SetSave&) { return value(); }
};


// service_traits::MD5Sum< ::ecu_msgs::SetSaveRequest> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetSave > 
template<>
struct MD5Sum< ::ecu_msgs::SetSaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetSave >::value();
  }
  static const char* value(const ::ecu_msgs::SetSaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetSaveRequest> should match 
// service_traits::DataType< ::ecu_msgs::SetSave > 
template<>
struct DataType< ::ecu_msgs::SetSaveRequest>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetSave >::value();
  }
  static const char* value(const ::ecu_msgs::SetSaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecu_msgs::SetSaveResponse> should match 
// service_traits::MD5Sum< ::ecu_msgs::SetSave > 
template<>
struct MD5Sum< ::ecu_msgs::SetSaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecu_msgs::SetSave >::value();
  }
  static const char* value(const ::ecu_msgs::SetSaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecu_msgs::SetSaveResponse> should match 
// service_traits::DataType< ::ecu_msgs::SetSave > 
template<>
struct DataType< ::ecu_msgs::SetSaveResponse>
{
  static const char* value()
  {
    return DataType< ::ecu_msgs::SetSave >::value();
  }
  static const char* value(const ::ecu_msgs::SetSaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECU_MSGS_MESSAGE_SETSAVE_H
