# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ecu_msgs/VehicleControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ecu_msgs.msg
import std_msgs.msg

class VehicleControl(genpy.Message):
  _md5sum = "c8b5113bd5fc6dbf622ebbca4f18f295"
  _type = "ecu_msgs/VehicleControl"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
TrackControl track_right
TrackControl track_left
bool breaks
bool lights

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ecu_msgs/TrackControl
float64 speed
bool break_status
"""
  __slots__ = ['header','track_right','track_left','breaks','lights']
  _slot_types = ['std_msgs/Header','ecu_msgs/TrackControl','ecu_msgs/TrackControl','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,track_right,track_left,breaks,lights

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_right is None:
        self.track_right = ecu_msgs.msg.TrackControl()
      if self.track_left is None:
        self.track_left = ecu_msgs.msg.TrackControl()
      if self.breaks is None:
        self.breaks = False
      if self.lights is None:
        self.lights = False
    else:
      self.header = std_msgs.msg.Header()
      self.track_right = ecu_msgs.msg.TrackControl()
      self.track_left = ecu_msgs.msg.TrackControl()
      self.breaks = False
      self.lights = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_dBd3B().pack(_x.track_right.speed, _x.track_right.break_status, _x.track_left.speed, _x.track_left.break_status, _x.breaks, _x.lights))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_right is None:
        self.track_right = ecu_msgs.msg.TrackControl()
      if self.track_left is None:
        self.track_left = ecu_msgs.msg.TrackControl()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.track_right.speed, _x.track_right.break_status, _x.track_left.speed, _x.track_left.break_status, _x.breaks, _x.lights,) = _get_struct_dBd3B().unpack(str[start:end])
      self.track_right.break_status = bool(self.track_right.break_status)
      self.track_left.break_status = bool(self.track_left.break_status)
      self.breaks = bool(self.breaks)
      self.lights = bool(self.lights)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_dBd3B().pack(_x.track_right.speed, _x.track_right.break_status, _x.track_left.speed, _x.track_left.break_status, _x.breaks, _x.lights))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_right is None:
        self.track_right = ecu_msgs.msg.TrackControl()
      if self.track_left is None:
        self.track_left = ecu_msgs.msg.TrackControl()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.track_right.speed, _x.track_right.break_status, _x.track_left.speed, _x.track_left.break_status, _x.breaks, _x.lights,) = _get_struct_dBd3B().unpack(str[start:end])
      self.track_right.break_status = bool(self.track_right.break_status)
      self.track_left.break_status = bool(self.track_left.break_status)
      self.breaks = bool(self.breaks)
      self.lights = bool(self.lights)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_dBd3B = None
def _get_struct_dBd3B():
    global _struct_dBd3B
    if _struct_dBd3B is None:
        _struct_dBd3B = struct.Struct("<dBd3B")
    return _struct_dBd3B
