# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from themis_msgs/DriveControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DriveControl(genpy.Message):
  _md5sum = "a3ab8998e46efefe9d244d241f9b70d1"
  _type = "themis_msgs/DriveControl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool enable
float32 x_axis
float32 y_axis
bool tank_mode
"""
  __slots__ = ['enable','x_axis','y_axis','tank_mode']
  _slot_types = ['bool','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enable,x_axis,y_axis,tank_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DriveControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.enable is None:
        self.enable = False
      if self.x_axis is None:
        self.x_axis = 0.
      if self.y_axis is None:
        self.y_axis = 0.
      if self.tank_mode is None:
        self.tank_mode = False
    else:
      self.enable = False
      self.x_axis = 0.
      self.y_axis = 0.
      self.tank_mode = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.enable, _x.x_axis, _x.y_axis, _x.tank_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.enable, _x.x_axis, _x.y_axis, _x.tank_mode,) = _get_struct_B2fB().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.tank_mode = bool(self.tank_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.enable, _x.x_axis, _x.y_axis, _x.tank_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.enable, _x.x_axis, _x.y_axis, _x.tank_mode,) = _get_struct_B2fB().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.tank_mode = bool(self.tank_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2fB = None
def _get_struct_B2fB():
    global _struct_B2fB
    if _struct_B2fB is None:
        _struct_B2fB = struct.Struct("<B2fB")
    return _struct_B2fB
