# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from themis_msgs/Generator.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import themis_msgs.msg

class Generator(genpy.Message):
  _md5sum = "b946db57ad5e2a3d65d4478369d1c9e1"
  _type = "themis_msgs/Generator"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """State state
float32 fuel_level
Sevcon sevcon
GeneratorPdm pdm

================================================================================
MSG: themis_msgs/State
uint16 id
string desc

================================================================================
MSG: themis_msgs/Sevcon
uint16 hour_count
int32 real_rpm
float32 real_torque
float32 battery_current
float32 battery_voltage
int16 motor_temp
int8 temp

================================================================================
MSG: themis_msgs/GeneratorPdm
float32 motor_coolant_temp
float32 engine_coolant_temp
"""
  __slots__ = ['state','fuel_level','sevcon','pdm']
  _slot_types = ['themis_msgs/State','float32','themis_msgs/Sevcon','themis_msgs/GeneratorPdm']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,fuel_level,sevcon,pdm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Generator, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = themis_msgs.msg.State()
      if self.fuel_level is None:
        self.fuel_level = 0.
      if self.sevcon is None:
        self.sevcon = themis_msgs.msg.Sevcon()
      if self.pdm is None:
        self.pdm = themis_msgs.msg.GeneratorPdm()
    else:
      self.state = themis_msgs.msg.State()
      self.fuel_level = 0.
      self.sevcon = themis_msgs.msg.Sevcon()
      self.pdm = themis_msgs.msg.GeneratorPdm()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_H().pack(self.state.id))
      _x = self.state.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fHi3fhb2f().pack(_x.fuel_level, _x.sevcon.hour_count, _x.sevcon.real_rpm, _x.sevcon.real_torque, _x.sevcon.battery_current, _x.sevcon.battery_voltage, _x.sevcon.motor_temp, _x.sevcon.temp, _x.pdm.motor_coolant_temp, _x.pdm.engine_coolant_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.state is None:
        self.state = themis_msgs.msg.State()
      if self.sevcon is None:
        self.sevcon = themis_msgs.msg.Sevcon()
      if self.pdm is None:
        self.pdm = themis_msgs.msg.GeneratorPdm()
      end = 0
      start = end
      end += 2
      (self.state.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.desc = str[start:end].decode('utf-8')
      else:
        self.state.desc = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.fuel_level, _x.sevcon.hour_count, _x.sevcon.real_rpm, _x.sevcon.real_torque, _x.sevcon.battery_current, _x.sevcon.battery_voltage, _x.sevcon.motor_temp, _x.sevcon.temp, _x.pdm.motor_coolant_temp, _x.pdm.engine_coolant_temp,) = _get_struct_fHi3fhb2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_H().pack(self.state.id))
      _x = self.state.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fHi3fhb2f().pack(_x.fuel_level, _x.sevcon.hour_count, _x.sevcon.real_rpm, _x.sevcon.real_torque, _x.sevcon.battery_current, _x.sevcon.battery_voltage, _x.sevcon.motor_temp, _x.sevcon.temp, _x.pdm.motor_coolant_temp, _x.pdm.engine_coolant_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.state is None:
        self.state = themis_msgs.msg.State()
      if self.sevcon is None:
        self.sevcon = themis_msgs.msg.Sevcon()
      if self.pdm is None:
        self.pdm = themis_msgs.msg.GeneratorPdm()
      end = 0
      start = end
      end += 2
      (self.state.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.desc = str[start:end].decode('utf-8')
      else:
        self.state.desc = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.fuel_level, _x.sevcon.hour_count, _x.sevcon.real_rpm, _x.sevcon.real_torque, _x.sevcon.battery_current, _x.sevcon.battery_voltage, _x.sevcon.motor_temp, _x.sevcon.temp, _x.pdm.motor_coolant_temp, _x.pdm.engine_coolant_temp,) = _get_struct_fHi3fhb2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_fHi3fhb2f = None
def _get_struct_fHi3fhb2f():
    global _struct_fHi3fhb2f
    if _struct_fHi3fhb2f is None:
        _struct_fHi3fhb2f = struct.Struct("<fHi3fhb2f")
    return _struct_fHi3fhb2f
