# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from themis_msgs/VehicleMode.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import themis_msgs.msg

class VehicleMode(genpy.Message):
  _md5sum = "565e3240233646eab93d6c6a27f36044"
  _type = "themis_msgs/VehicleMode"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """State vehicle
State generator
State speed
State brake
State charge

================================================================================
MSG: themis_msgs/State
uint16 id
string desc
"""
  __slots__ = ['vehicle','generator','speed','brake','charge']
  _slot_types = ['themis_msgs/State','themis_msgs/State','themis_msgs/State','themis_msgs/State','themis_msgs/State']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicle,generator,speed,brake,charge

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleMode, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vehicle is None:
        self.vehicle = themis_msgs.msg.State()
      if self.generator is None:
        self.generator = themis_msgs.msg.State()
      if self.speed is None:
        self.speed = themis_msgs.msg.State()
      if self.brake is None:
        self.brake = themis_msgs.msg.State()
      if self.charge is None:
        self.charge = themis_msgs.msg.State()
    else:
      self.vehicle = themis_msgs.msg.State()
      self.generator = themis_msgs.msg.State()
      self.speed = themis_msgs.msg.State()
      self.brake = themis_msgs.msg.State()
      self.charge = themis_msgs.msg.State()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_H().pack(self.vehicle.id))
      _x = self.vehicle.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.generator.id))
      _x = self.generator.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.speed.id))
      _x = self.speed.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.brake.id))
      _x = self.brake.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.charge.id))
      _x = self.charge.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.vehicle is None:
        self.vehicle = themis_msgs.msg.State()
      if self.generator is None:
        self.generator = themis_msgs.msg.State()
      if self.speed is None:
        self.speed = themis_msgs.msg.State()
      if self.brake is None:
        self.brake = themis_msgs.msg.State()
      if self.charge is None:
        self.charge = themis_msgs.msg.State()
      end = 0
      start = end
      end += 2
      (self.vehicle.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle.desc = str[start:end].decode('utf-8')
      else:
        self.vehicle.desc = str[start:end]
      start = end
      end += 2
      (self.generator.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.generator.desc = str[start:end].decode('utf-8')
      else:
        self.generator.desc = str[start:end]
      start = end
      end += 2
      (self.speed.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.speed.desc = str[start:end].decode('utf-8')
      else:
        self.speed.desc = str[start:end]
      start = end
      end += 2
      (self.brake.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.brake.desc = str[start:end].decode('utf-8')
      else:
        self.brake.desc = str[start:end]
      start = end
      end += 2
      (self.charge.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.charge.desc = str[start:end].decode('utf-8')
      else:
        self.charge.desc = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_H().pack(self.vehicle.id))
      _x = self.vehicle.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.generator.id))
      _x = self.generator.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.speed.id))
      _x = self.speed.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.brake.id))
      _x = self.brake.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_H().pack(self.charge.id))
      _x = self.charge.desc
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.vehicle is None:
        self.vehicle = themis_msgs.msg.State()
      if self.generator is None:
        self.generator = themis_msgs.msg.State()
      if self.speed is None:
        self.speed = themis_msgs.msg.State()
      if self.brake is None:
        self.brake = themis_msgs.msg.State()
      if self.charge is None:
        self.charge = themis_msgs.msg.State()
      end = 0
      start = end
      end += 2
      (self.vehicle.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle.desc = str[start:end].decode('utf-8')
      else:
        self.vehicle.desc = str[start:end]
      start = end
      end += 2
      (self.generator.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.generator.desc = str[start:end].decode('utf-8')
      else:
        self.generator.desc = str[start:end]
      start = end
      end += 2
      (self.speed.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.speed.desc = str[start:end].decode('utf-8')
      else:
        self.speed.desc = str[start:end]
      start = end
      end += 2
      (self.brake.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.brake.desc = str[start:end].decode('utf-8')
      else:
        self.brake.desc = str[start:end]
      start = end
      end += 2
      (self.charge.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.charge.desc = str[start:end].decode('utf-8')
      else:
        self.charge.desc = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
