// Generated by gencpp from file themis_msgs/Battery.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_BATTERY_H
#define THEMIS_MSGS_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <themis_msgs/State.h>

namespace themis_msgs
{
template <class ContainerAllocator>
struct Battery_
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
    : air_state()
    , low_voltage(0.0)
    , high_voltage(0.0)
    , charge_level(0.0)  {
    }
  Battery_(const ContainerAllocator& _alloc)
    : air_state(_alloc)
    , low_voltage(0.0)
    , high_voltage(0.0)
    , charge_level(0.0)  {
  (void)_alloc;
    }



   typedef  ::themis_msgs::State_<ContainerAllocator>  _air_state_type;
  _air_state_type air_state;

   typedef float _low_voltage_type;
  _low_voltage_type low_voltage;

   typedef float _high_voltage_type;
  _high_voltage_type high_voltage;

   typedef float _charge_level_type;
  _charge_level_type charge_level;





  typedef boost::shared_ptr< ::themis_msgs::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::Battery_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_

typedef ::themis_msgs::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::themis_msgs::Battery > BatteryPtr;
typedef boost::shared_ptr< ::themis_msgs::Battery const> BatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::Battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::Battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Battery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12a9585c62ecbcc51a9af404d663e576";
  }

  static const char* value(const ::themis_msgs::Battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12a9585c62ecbcc5ULL;
  static const uint64_t static_value2 = 0x1a9af404d663e576ULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/Battery";
  }

  static const char* value(const ::themis_msgs::Battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State air_state\n"
"float32 low_voltage\n"
"float32 high_voltage\n"
"float32 charge_level\n"
"\n"
"# uint16 UNDEFINED_STATE = 0\n"
"# uint16 INIT_STATE = 1\n"
"# uint16 OFF_STATE = 2\n"
"# uint16 SWITCH_ON_STATE = 3\n"
"# uint16 ON_STATE = 4\n"
"# uint16 SWITCH_OFF_STATE = 5\n"
"# uint16 CHARGE_STATE = 6\n"
"\n"
"================================================================================\n"
"MSG: themis_msgs/State\n"
"uint16 id\n"
"string desc\n"
;
  }

  static const char* value(const ::themis_msgs::Battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::Battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.air_state);
      stream.next(m.low_voltage);
      stream.next(m.high_voltage);
      stream.next(m.charge_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::Battery_<ContainerAllocator>& v)
  {
    s << indent << "air_state: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.air_state);
    s << indent << "low_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.low_voltage);
    s << indent << "high_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.high_voltage);
    s << indent << "charge_level: ";
    Printer<float>::stream(s, indent + "  ", v.charge_level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_BATTERY_H
