// Generated by gencpp from file themis_msgs/GeneratorPdm.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_GENERATORPDM_H
#define THEMIS_MSGS_MESSAGE_GENERATORPDM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace themis_msgs
{
template <class ContainerAllocator>
struct GeneratorPdm_
{
  typedef GeneratorPdm_<ContainerAllocator> Type;

  GeneratorPdm_()
    : motor_coolant_temp(0.0)
    , engine_coolant_temp(0.0)  {
    }
  GeneratorPdm_(const ContainerAllocator& _alloc)
    : motor_coolant_temp(0.0)
    , engine_coolant_temp(0.0)  {
  (void)_alloc;
    }



   typedef float _motor_coolant_temp_type;
  _motor_coolant_temp_type motor_coolant_temp;

   typedef float _engine_coolant_temp_type;
  _engine_coolant_temp_type engine_coolant_temp;





  typedef boost::shared_ptr< ::themis_msgs::GeneratorPdm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::GeneratorPdm_<ContainerAllocator> const> ConstPtr;

}; // struct GeneratorPdm_

typedef ::themis_msgs::GeneratorPdm_<std::allocator<void> > GeneratorPdm;

typedef boost::shared_ptr< ::themis_msgs::GeneratorPdm > GeneratorPdmPtr;
typedef boost::shared_ptr< ::themis_msgs::GeneratorPdm const> GeneratorPdmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::GeneratorPdm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::GeneratorPdm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::GeneratorPdm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::GeneratorPdm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25d429d660d1faae2c98790eb6d65e0e";
  }

  static const char* value(const ::themis_msgs::GeneratorPdm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25d429d660d1faaeULL;
  static const uint64_t static_value2 = 0x2c98790eb6d65e0eULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/GeneratorPdm";
  }

  static const char* value(const ::themis_msgs::GeneratorPdm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor_coolant_temp\n"
"float32 engine_coolant_temp\n"
;
  }

  static const char* value(const ::themis_msgs::GeneratorPdm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_coolant_temp);
      stream.next(m.engine_coolant_temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneratorPdm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::GeneratorPdm_<ContainerAllocator>& v)
  {
    s << indent << "motor_coolant_temp: ";
    Printer<float>::stream(s, indent + "  ", v.motor_coolant_temp);
    s << indent << "engine_coolant_temp: ";
    Printer<float>::stream(s, indent + "  ", v.engine_coolant_temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_GENERATORPDM_H
