// Generated by gencpp from file themis_msgs/Generator.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_GENERATOR_H
#define THEMIS_MSGS_MESSAGE_GENERATOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <themis_msgs/State.h>
#include <themis_msgs/Sevcon.h>
#include <themis_msgs/GeneratorPdm.h>

namespace themis_msgs
{
template <class ContainerAllocator>
struct Generator_
{
  typedef Generator_<ContainerAllocator> Type;

  Generator_()
    : state()
    , fuel_level(0.0)
    , sevcon()
    , pdm()  {
    }
  Generator_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , fuel_level(0.0)
    , sevcon(_alloc)
    , pdm(_alloc)  {
  (void)_alloc;
    }



   typedef  ::themis_msgs::State_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef float _fuel_level_type;
  _fuel_level_type fuel_level;

   typedef  ::themis_msgs::Sevcon_<ContainerAllocator>  _sevcon_type;
  _sevcon_type sevcon;

   typedef  ::themis_msgs::GeneratorPdm_<ContainerAllocator>  _pdm_type;
  _pdm_type pdm;





  typedef boost::shared_ptr< ::themis_msgs::Generator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::Generator_<ContainerAllocator> const> ConstPtr;

}; // struct Generator_

typedef ::themis_msgs::Generator_<std::allocator<void> > Generator;

typedef boost::shared_ptr< ::themis_msgs::Generator > GeneratorPtr;
typedef boost::shared_ptr< ::themis_msgs::Generator const> GeneratorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::Generator_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::Generator_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Generator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Generator_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Generator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Generator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Generator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Generator_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::Generator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b946db57ad5e2a3d65d4478369d1c9e1";
  }

  static const char* value(const ::themis_msgs::Generator_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb946db57ad5e2a3dULL;
  static const uint64_t static_value2 = 0x65d4478369d1c9e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::Generator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/Generator";
  }

  static const char* value(const ::themis_msgs::Generator_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::Generator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State state\n"
"float32 fuel_level\n"
"Sevcon sevcon\n"
"GeneratorPdm pdm\n"
"\n"
"================================================================================\n"
"MSG: themis_msgs/State\n"
"uint16 id\n"
"string desc\n"
"\n"
"================================================================================\n"
"MSG: themis_msgs/Sevcon\n"
"uint16 hour_count\n"
"int32 real_rpm\n"
"float32 real_torque\n"
"float32 battery_current\n"
"float32 battery_voltage\n"
"int16 motor_temp\n"
"int8 temp\n"
"\n"
"================================================================================\n"
"MSG: themis_msgs/GeneratorPdm\n"
"float32 motor_coolant_temp\n"
"float32 engine_coolant_temp\n"
;
  }

  static const char* value(const ::themis_msgs::Generator_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::Generator_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.fuel_level);
      stream.next(m.sevcon);
      stream.next(m.pdm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Generator_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::Generator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::Generator_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "fuel_level: ";
    Printer<float>::stream(s, indent + "  ", v.fuel_level);
    s << indent << "sevcon: ";
    s << std::endl;
    Printer< ::themis_msgs::Sevcon_<ContainerAllocator> >::stream(s, indent + "  ", v.sevcon);
    s << indent << "pdm: ";
    s << std::endl;
    Printer< ::themis_msgs::GeneratorPdm_<ContainerAllocator> >::stream(s, indent + "  ", v.pdm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_GENERATOR_H
