// Generated by gencpp from file themis_msgs/ModeControl.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_MODECONTROL_H
#define THEMIS_MSGS_MESSAGE_MODECONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace themis_msgs
{
template <class ContainerAllocator>
struct ModeControl_
{
  typedef ModeControl_<ContainerAllocator> Type;

  ModeControl_()
    : vehicle(0)
    , generator(0)
    , speed(0)
    , brake(0)
    , charge(0)  {
    }
  ModeControl_(const ContainerAllocator& _alloc)
    : vehicle(0)
    , generator(0)
    , speed(0)
    , brake(0)
    , charge(0)  {
  (void)_alloc;
    }



   typedef uint8_t _vehicle_type;
  _vehicle_type vehicle;

   typedef uint8_t _generator_type;
  _generator_type generator;

   typedef uint8_t _speed_type;
  _speed_type speed;

   typedef uint8_t _brake_type;
  _brake_type brake;

   typedef uint8_t _charge_type;
  _charge_type charge;





  typedef boost::shared_ptr< ::themis_msgs::ModeControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::ModeControl_<ContainerAllocator> const> ConstPtr;

}; // struct ModeControl_

typedef ::themis_msgs::ModeControl_<std::allocator<void> > ModeControl;

typedef boost::shared_ptr< ::themis_msgs::ModeControl > ModeControlPtr;
typedef boost::shared_ptr< ::themis_msgs::ModeControl const> ModeControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::ModeControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::ModeControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::ModeControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::ModeControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::ModeControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::ModeControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::ModeControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::ModeControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::ModeControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad5484922684f97570b593292ada2bf9";
  }

  static const char* value(const ::themis_msgs::ModeControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad5484922684f975ULL;
  static const uint64_t static_value2 = 0x70b593292ada2bf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::ModeControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/ModeControl";
  }

  static const char* value(const ::themis_msgs::ModeControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::ModeControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 vehicle\n"
"uint8 generator\n"
"uint8 speed\n"
"uint8 brake\n"
"uint8 charge\n"
;
  }

  static const char* value(const ::themis_msgs::ModeControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::ModeControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle);
      stream.next(m.generator);
      stream.next(m.speed);
      stream.next(m.brake);
      stream.next(m.charge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::ModeControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::ModeControl_<ContainerAllocator>& v)
  {
    s << indent << "vehicle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle);
    s << indent << "generator: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.generator);
    s << indent << "speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
    s << indent << "charge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_MODECONTROL_H
