// Generated by gencpp from file themis_msgs/RpmMessage.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_RPMMESSAGE_H
#define THEMIS_MSGS_MESSAGE_RPMMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace themis_msgs
{
template <class ContainerAllocator>
struct RpmMessage_
{
  typedef RpmMessage_<ContainerAllocator> Type;

  RpmMessage_()
    : header()
    , right_rpm(0.0)
    , left_rpm(0.0)  {
    }
  RpmMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , right_rpm(0.0)
    , left_rpm(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _right_rpm_type;
  _right_rpm_type right_rpm;

   typedef float _left_rpm_type;
  _left_rpm_type left_rpm;





  typedef boost::shared_ptr< ::themis_msgs::RpmMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::RpmMessage_<ContainerAllocator> const> ConstPtr;

}; // struct RpmMessage_

typedef ::themis_msgs::RpmMessage_<std::allocator<void> > RpmMessage;

typedef boost::shared_ptr< ::themis_msgs::RpmMessage > RpmMessagePtr;
typedef boost::shared_ptr< ::themis_msgs::RpmMessage const> RpmMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::RpmMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::RpmMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::RpmMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::RpmMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::RpmMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::RpmMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::RpmMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::RpmMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::RpmMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c558b79200b384ff5f1b5baf8d2c219a";
  }

  static const char* value(const ::themis_msgs::RpmMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc558b79200b384ffULL;
  static const uint64_t static_value2 = 0x5f1b5baf8d2c219aULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::RpmMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/RpmMessage";
  }

  static const char* value(const ::themis_msgs::RpmMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::RpmMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 right_rpm\n"
"float32 left_rpm\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::themis_msgs::RpmMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::RpmMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.right_rpm);
      stream.next(m.left_rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RpmMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::RpmMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::RpmMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "right_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.right_rpm);
    s << indent << "left_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.left_rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_RPMMESSAGE_H
