// Generated by gencpp from file themis_msgs/SetState.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_SETSTATE_H
#define THEMIS_MSGS_MESSAGE_SETSTATE_H

#include <ros/service_traits.h>


#include <themis_msgs/SetStateRequest.h>
#include <themis_msgs/SetStateResponse.h>


namespace themis_msgs
{

struct SetState
{

typedef SetStateRequest Request;
typedef SetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetState
} // namespace themis_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::themis_msgs::SetState > {
  static const char* value()
  {
    return "ce0eba33c969c78d3ee94cf138cc41e2";
  }

  static const char* value(const ::themis_msgs::SetState&) { return value(); }
};

template<>
struct DataType< ::themis_msgs::SetState > {
  static const char* value()
  {
    return "themis_msgs/SetState";
  }

  static const char* value(const ::themis_msgs::SetState&) { return value(); }
};


// service_traits::MD5Sum< ::themis_msgs::SetStateRequest> should match 
// service_traits::MD5Sum< ::themis_msgs::SetState > 
template<>
struct MD5Sum< ::themis_msgs::SetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::themis_msgs::SetState >::value();
  }
  static const char* value(const ::themis_msgs::SetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::themis_msgs::SetStateRequest> should match 
// service_traits::DataType< ::themis_msgs::SetState > 
template<>
struct DataType< ::themis_msgs::SetStateRequest>
{
  static const char* value()
  {
    return DataType< ::themis_msgs::SetState >::value();
  }
  static const char* value(const ::themis_msgs::SetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::themis_msgs::SetStateResponse> should match 
// service_traits::MD5Sum< ::themis_msgs::SetState > 
template<>
struct MD5Sum< ::themis_msgs::SetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::themis_msgs::SetState >::value();
  }
  static const char* value(const ::themis_msgs::SetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::themis_msgs::SetStateResponse> should match 
// service_traits::DataType< ::themis_msgs::SetState > 
template<>
struct DataType< ::themis_msgs::SetStateResponse>
{
  static const char* value()
  {
    return DataType< ::themis_msgs::SetState >::value();
  }
  static const char* value(const ::themis_msgs::SetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_SETSTATE_H
