// Generated by gencpp from file themis_msgs/Sevcon.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_SEVCON_H
#define THEMIS_MSGS_MESSAGE_SEVCON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace themis_msgs
{
template <class ContainerAllocator>
struct Sevcon_
{
  typedef Sevcon_<ContainerAllocator> Type;

  Sevcon_()
    : hour_count(0)
    , real_rpm(0)
    , real_torque(0.0)
    , battery_current(0.0)
    , battery_voltage(0.0)
    , motor_temp(0)
    , temp(0)  {
    }
  Sevcon_(const ContainerAllocator& _alloc)
    : hour_count(0)
    , real_rpm(0)
    , real_torque(0.0)
    , battery_current(0.0)
    , battery_voltage(0.0)
    , motor_temp(0)
    , temp(0)  {
  (void)_alloc;
    }



   typedef uint16_t _hour_count_type;
  _hour_count_type hour_count;

   typedef int32_t _real_rpm_type;
  _real_rpm_type real_rpm;

   typedef float _real_torque_type;
  _real_torque_type real_torque;

   typedef float _battery_current_type;
  _battery_current_type battery_current;

   typedef float _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef int16_t _motor_temp_type;
  _motor_temp_type motor_temp;

   typedef int8_t _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::themis_msgs::Sevcon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::Sevcon_<ContainerAllocator> const> ConstPtr;

}; // struct Sevcon_

typedef ::themis_msgs::Sevcon_<std::allocator<void> > Sevcon;

typedef boost::shared_ptr< ::themis_msgs::Sevcon > SevconPtr;
typedef boost::shared_ptr< ::themis_msgs::Sevcon const> SevconConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::Sevcon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::Sevcon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Sevcon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::Sevcon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Sevcon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::Sevcon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Sevcon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::Sevcon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::Sevcon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b11f79be0926a6b4515869450f7d6aa";
  }

  static const char* value(const ::themis_msgs::Sevcon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b11f79be0926a6bULL;
  static const uint64_t static_value2 = 0x4515869450f7d6aaULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::Sevcon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/Sevcon";
  }

  static const char* value(const ::themis_msgs::Sevcon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::Sevcon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 hour_count\n"
"int32 real_rpm\n"
"float32 real_torque\n"
"float32 battery_current\n"
"float32 battery_voltage\n"
"int16 motor_temp\n"
"int8 temp\n"
;
  }

  static const char* value(const ::themis_msgs::Sevcon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::Sevcon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hour_count);
      stream.next(m.real_rpm);
      stream.next(m.real_torque);
      stream.next(m.battery_current);
      stream.next(m.battery_voltage);
      stream.next(m.motor_temp);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sevcon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::Sevcon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::Sevcon_<ContainerAllocator>& v)
  {
    s << indent << "hour_count: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hour_count);
    s << indent << "real_rpm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.real_rpm);
    s << indent << "real_torque: ";
    Printer<float>::stream(s, indent + "  ", v.real_torque);
    s << indent << "battery_current: ";
    Printer<float>::stream(s, indent + "  ", v.battery_current);
    s << indent << "battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "motor_temp: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_temp);
    s << indent << "temp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_SEVCON_H
