// Generated by gencpp from file themis_msgs/VehicleMode.msg
// DO NOT EDIT!


#ifndef THEMIS_MSGS_MESSAGE_VEHICLEMODE_H
#define THEMIS_MSGS_MESSAGE_VEHICLEMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <themis_msgs/State.h>
#include <themis_msgs/State.h>
#include <themis_msgs/State.h>
#include <themis_msgs/State.h>
#include <themis_msgs/State.h>

namespace themis_msgs
{
template <class ContainerAllocator>
struct VehicleMode_
{
  typedef VehicleMode_<ContainerAllocator> Type;

  VehicleMode_()
    : vehicle()
    , generator()
    , speed()
    , brake()
    , charge()  {
    }
  VehicleMode_(const ContainerAllocator& _alloc)
    : vehicle(_alloc)
    , generator(_alloc)
    , speed(_alloc)
    , brake(_alloc)
    , charge(_alloc)  {
  (void)_alloc;
    }



   typedef  ::themis_msgs::State_<ContainerAllocator>  _vehicle_type;
  _vehicle_type vehicle;

   typedef  ::themis_msgs::State_<ContainerAllocator>  _generator_type;
  _generator_type generator;

   typedef  ::themis_msgs::State_<ContainerAllocator>  _speed_type;
  _speed_type speed;

   typedef  ::themis_msgs::State_<ContainerAllocator>  _brake_type;
  _brake_type brake;

   typedef  ::themis_msgs::State_<ContainerAllocator>  _charge_type;
  _charge_type charge;





  typedef boost::shared_ptr< ::themis_msgs::VehicleMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::themis_msgs::VehicleMode_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleMode_

typedef ::themis_msgs::VehicleMode_<std::allocator<void> > VehicleMode;

typedef boost::shared_ptr< ::themis_msgs::VehicleMode > VehicleModePtr;
typedef boost::shared_ptr< ::themis_msgs::VehicleMode const> VehicleModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::themis_msgs::VehicleMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::themis_msgs::VehicleMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace themis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'themis_msgs': ['/home/user/milrem/src/themis_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::VehicleMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::themis_msgs::VehicleMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::VehicleMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::themis_msgs::VehicleMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::VehicleMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::themis_msgs::VehicleMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::themis_msgs::VehicleMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "565e3240233646eab93d6c6a27f36044";
  }

  static const char* value(const ::themis_msgs::VehicleMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x565e3240233646eaULL;
  static const uint64_t static_value2 = 0xb93d6c6a27f36044ULL;
};

template<class ContainerAllocator>
struct DataType< ::themis_msgs::VehicleMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "themis_msgs/VehicleMode";
  }

  static const char* value(const ::themis_msgs::VehicleMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::themis_msgs::VehicleMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State vehicle\n"
"State generator\n"
"State speed\n"
"State brake\n"
"State charge\n"
"\n"
"================================================================================\n"
"MSG: themis_msgs/State\n"
"uint16 id\n"
"string desc\n"
;
  }

  static const char* value(const ::themis_msgs::VehicleMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::themis_msgs::VehicleMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle);
      stream.next(m.generator);
      stream.next(m.speed);
      stream.next(m.brake);
      stream.next(m.charge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::themis_msgs::VehicleMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::themis_msgs::VehicleMode_<ContainerAllocator>& v)
  {
    s << indent << "vehicle: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle);
    s << indent << "generator: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.generator);
    s << indent << "speed: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.speed);
    s << indent << "brake: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.brake);
    s << indent << "charge: ";
    s << std::endl;
    Printer< ::themis_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.charge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THEMIS_MSGS_MESSAGE_VEHICLEMODE_H
