// Generated by gencpp from file iseauto/Power.msg
// DO NOT EDIT!


#ifndef ISEAUTO_MESSAGE_POWER_H
#define ISEAUTO_MESSAGE_POWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iseauto
{
template <class ContainerAllocator>
struct Power_
{
  typedef Power_<ContainerAllocator> Type;

  Power_()
    : phase1(0.0)
    , phase2(0.0)
    , phase3(0.0)
    , total(0.0)  {
    }
  Power_(const ContainerAllocator& _alloc)
    : phase1(0.0)
    , phase2(0.0)
    , phase3(0.0)
    , total(0.0)  {
  (void)_alloc;
    }



   typedef float _phase1_type;
  _phase1_type phase1;

   typedef float _phase2_type;
  _phase2_type phase2;

   typedef float _phase3_type;
  _phase3_type phase3;

   typedef float _total_type;
  _total_type total;





  typedef boost::shared_ptr< ::iseauto::Power_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iseauto::Power_<ContainerAllocator> const> ConstPtr;

}; // struct Power_

typedef ::iseauto::Power_<std::allocator<void> > Power;

typedef boost::shared_ptr< ::iseauto::Power > PowerPtr;
typedef boost::shared_ptr< ::iseauto::Power const> PowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iseauto::Power_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iseauto::Power_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iseauto::Power_<ContainerAllocator1> & lhs, const ::iseauto::Power_<ContainerAllocator2> & rhs)
{
  return lhs.phase1 == rhs.phase1 &&
    lhs.phase2 == rhs.phase2 &&
    lhs.phase3 == rhs.phase3 &&
    lhs.total == rhs.total;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iseauto::Power_<ContainerAllocator1> & lhs, const ::iseauto::Power_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iseauto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iseauto::Power_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iseauto::Power_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iseauto::Power_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iseauto::Power_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iseauto::Power_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iseauto::Power_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iseauto::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2da61ddd54b46d41de22ff847920071c";
  }

  static const char* value(const ::iseauto::Power_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2da61ddd54b46d41ULL;
  static const uint64_t static_value2 = 0xde22ff847920071cULL;
};

template<class ContainerAllocator>
struct DataType< ::iseauto::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iseauto/Power";
  }

  static const char* value(const ::iseauto::Power_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iseauto::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 phase1\n"
"float32 phase2\n"
"float32 phase3\n"
"float32 total\n"
;
  }

  static const char* value(const ::iseauto::Power_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iseauto::Power_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase1);
      stream.next(m.phase2);
      stream.next(m.phase3);
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Power_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iseauto::Power_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iseauto::Power_<ContainerAllocator>& v)
  {
    s << indent << "phase1: ";
    Printer<float>::stream(s, indent + "  ", v.phase1);
    s << indent << "phase2: ";
    Printer<float>::stream(s, indent + "  ", v.phase2);
    s << indent << "phase3: ";
    Printer<float>::stream(s, indent + "  ", v.phase3);
    s << indent << "total: ";
    Printer<float>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISEAUTO_MESSAGE_POWER_H
