// Generated by gencpp from file iseauto/Voltage.msg
// DO NOT EDIT!


#ifndef ISEAUTO_MESSAGE_VOLTAGE_H
#define ISEAUTO_MESSAGE_VOLTAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iseauto
{
template <class ContainerAllocator>
struct Voltage_
{
  typedef Voltage_<ContainerAllocator> Type;

  Voltage_()
    : voltage1(0.0)
    , voltage2(0.0)
    , voltage3(0.0)  {
    }
  Voltage_(const ContainerAllocator& _alloc)
    : voltage1(0.0)
    , voltage2(0.0)
    , voltage3(0.0)  {
  (void)_alloc;
    }



   typedef float _voltage1_type;
  _voltage1_type voltage1;

   typedef float _voltage2_type;
  _voltage2_type voltage2;

   typedef float _voltage3_type;
  _voltage3_type voltage3;





  typedef boost::shared_ptr< ::iseauto::Voltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iseauto::Voltage_<ContainerAllocator> const> ConstPtr;

}; // struct Voltage_

typedef ::iseauto::Voltage_<std::allocator<void> > Voltage;

typedef boost::shared_ptr< ::iseauto::Voltage > VoltagePtr;
typedef boost::shared_ptr< ::iseauto::Voltage const> VoltageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iseauto::Voltage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iseauto::Voltage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iseauto::Voltage_<ContainerAllocator1> & lhs, const ::iseauto::Voltage_<ContainerAllocator2> & rhs)
{
  return lhs.voltage1 == rhs.voltage1 &&
    lhs.voltage2 == rhs.voltage2 &&
    lhs.voltage3 == rhs.voltage3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iseauto::Voltage_<ContainerAllocator1> & lhs, const ::iseauto::Voltage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iseauto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iseauto::Voltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iseauto::Voltage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iseauto::Voltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iseauto::Voltage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iseauto::Voltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iseauto::Voltage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iseauto::Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "201ad7f8e98b5d0b734069bf861aba7a";
  }

  static const char* value(const ::iseauto::Voltage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x201ad7f8e98b5d0bULL;
  static const uint64_t static_value2 = 0x734069bf861aba7aULL;
};

template<class ContainerAllocator>
struct DataType< ::iseauto::Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iseauto/Voltage";
  }

  static const char* value(const ::iseauto::Voltage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iseauto::Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 voltage1\n"
"float32 voltage2\n"
"float32 voltage3\n"
;
  }

  static const char* value(const ::iseauto::Voltage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iseauto::Voltage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage1);
      stream.next(m.voltage2);
      stream.next(m.voltage3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Voltage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iseauto::Voltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iseauto::Voltage_<ContainerAllocator>& v)
  {
    s << indent << "voltage1: ";
    Printer<float>::stream(s, indent + "  ", v.voltage1);
    s << indent << "voltage2: ";
    Printer<float>::stream(s, indent + "  ", v.voltage2);
    s << indent << "voltage3: ";
    Printer<float>::stream(s, indent + "  ", v.voltage3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISEAUTO_MESSAGE_VOLTAGE_H
