// Generated by gencpp from file agv_msgs/CurrentPathStatus.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_CURRENTPATHSTATUS_H
#define AGV_MSGS_MESSAGE_CURRENTPATHSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <agv_msgs/NavPath.h>
#include <agv_msgs/PathSegmentInfo.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct CurrentPathStatus_
{
  typedef CurrentPathStatus_<ContainerAllocator> Type;

  CurrentPathStatus_()
    : header()
    , path()
    , blockages()
    , planner_name()
    , revision(0)  {
    }
  CurrentPathStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , path(_alloc)
    , blockages(_alloc)
    , planner_name(_alloc)
    , revision(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::agv_msgs::NavPath_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef std::vector< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >::other >  _blockages_type;
  _blockages_type blockages;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _planner_name_type;
  _planner_name_type planner_name;

   typedef uint16_t _revision_type;
  _revision_type revision;





  typedef boost::shared_ptr< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentPathStatus_

typedef ::agv_msgs::CurrentPathStatus_<std::allocator<void> > CurrentPathStatus;

typedef boost::shared_ptr< ::agv_msgs::CurrentPathStatus > CurrentPathStatusPtr;
typedef boost::shared_ptr< ::agv_msgs::CurrentPathStatus const> CurrentPathStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::CurrentPathStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'agv_msgs': ['/home/user/milrem/src/agv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea2564236946447786963cb1fb92e625";
  }

  static const char* value(const ::agv_msgs::CurrentPathStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea25642369464477ULL;
  static const uint64_t static_value2 = 0x86963cb1fb92e625ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/CurrentPathStatus";
  }

  static const char* value(const ::agv_msgs::CurrentPathStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"agv_msgs/NavPath path\n"
"agv_msgs/PathSegmentInfo[] blockages\n"
"string planner_name\n"
"uint16 revision\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/NavPath\n"
"string[] ids\n"
"uint16 type\n"
"================================================================================\n"
"MSG: agv_msgs/PathSegmentInfo\n"
"string start_id\n"
"string end_id\n"
"float32 distance\n"
;
  }

  static const char* value(const ::agv_msgs::CurrentPathStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.path);
      stream.next(m.blockages);
      stream.next(m.planner_name);
      stream.next(m.revision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentPathStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::CurrentPathStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::CurrentPathStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "path: ";
    s << std::endl;
    Printer< ::agv_msgs::NavPath_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "blockages[]" << std::endl;
    for (size_t i = 0; i < v.blockages.size(); ++i)
    {
      s << indent << "  blockages[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.blockages[i]);
    }
    s << indent << "planner_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.planner_name);
    s << indent << "revision: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.revision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_CURRENTPATHSTATUS_H
