// Generated by gencpp from file agv_msgs/NavPaths.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_NAVPATHS_H
#define AGV_MSGS_MESSAGE_NAVPATHS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_msgs/NavPath.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct NavPaths_
{
  typedef NavPaths_<ContainerAllocator> Type;

  NavPaths_()
    : paths()  {
    }
  NavPaths_(const ContainerAllocator& _alloc)
    : paths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::agv_msgs::NavPath_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::agv_msgs::NavPath_<ContainerAllocator> >::other >  _paths_type;
  _paths_type paths;





  typedef boost::shared_ptr< ::agv_msgs::NavPaths_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::NavPaths_<ContainerAllocator> const> ConstPtr;

}; // struct NavPaths_

typedef ::agv_msgs::NavPaths_<std::allocator<void> > NavPaths;

typedef boost::shared_ptr< ::agv_msgs::NavPaths > NavPathsPtr;
typedef boost::shared_ptr< ::agv_msgs::NavPaths const> NavPathsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::NavPaths_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::NavPaths_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'agv_msgs': ['/home/user/milrem/src/agv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::NavPaths_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::NavPaths_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::NavPaths_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::NavPaths_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::NavPaths_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::NavPaths_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::NavPaths_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8ca5b9769932f260f0331e043f67520";
  }

  static const char* value(const ::agv_msgs::NavPaths_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8ca5b9769932f26ULL;
  static const uint64_t static_value2 = 0x0f0331e043f67520ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::NavPaths_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/NavPaths";
  }

  static const char* value(const ::agv_msgs::NavPaths_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::NavPaths_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NavPath[] paths\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/NavPath\n"
"string[] ids\n"
"uint16 type\n"
;
  }

  static const char* value(const ::agv_msgs::NavPaths_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::NavPaths_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavPaths_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::NavPaths_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::NavPaths_<ContainerAllocator>& v)
  {
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::NavPath_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_NAVPATHS_H
