// Generated by gencpp from file agv_msgs/PathSegmentInfo.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_PATHSEGMENTINFO_H
#define AGV_MSGS_MESSAGE_PATHSEGMENTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct PathSegmentInfo_
{
  typedef PathSegmentInfo_<ContainerAllocator> Type;

  PathSegmentInfo_()
    : start_id()
    , end_id()
    , distance(0.0)  {
    }
  PathSegmentInfo_(const ContainerAllocator& _alloc)
    : start_id(_alloc)
    , end_id(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_id_type;
  _start_id_type start_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _end_id_type;
  _end_id_type end_id;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> const> ConstPtr;

}; // struct PathSegmentInfo_

typedef ::agv_msgs::PathSegmentInfo_<std::allocator<void> > PathSegmentInfo;

typedef boost::shared_ptr< ::agv_msgs::PathSegmentInfo > PathSegmentInfoPtr;
typedef boost::shared_ptr< ::agv_msgs::PathSegmentInfo const> PathSegmentInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::PathSegmentInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'agv_msgs': ['/home/user/milrem/src/agv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1177108c776ff861a843c40f49c83e33";
  }

  static const char* value(const ::agv_msgs::PathSegmentInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1177108c776ff861ULL;
  static const uint64_t static_value2 = 0xa843c40f49c83e33ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/PathSegmentInfo";
  }

  static const char* value(const ::agv_msgs::PathSegmentInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string start_id\n"
"string end_id\n"
"float32 distance\n"
;
  }

  static const char* value(const ::agv_msgs::PathSegmentInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_id);
      stream.next(m.end_id);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathSegmentInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::PathSegmentInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::PathSegmentInfo_<ContainerAllocator>& v)
  {
    s << indent << "start_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start_id);
    s << indent << "end_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.end_id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_PATHSEGMENTINFO_H
