// Generated by gencpp from file agv_msgs/WaypointArrayStamped.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_WAYPOINTARRAYSTAMPED_H
#define AGV_MSGS_MESSAGE_WAYPOINTARRAYSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <agv_msgs/Waypoint.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct WaypointArrayStamped_
{
  typedef WaypointArrayStamped_<ContainerAllocator> Type;

  WaypointArrayStamped_()
    : header()
    , points()
    , revision(0)  {
    }
  WaypointArrayStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)
    , revision(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::agv_msgs::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::agv_msgs::Waypoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef uint16_t _revision_type;
  _revision_type revision;





  typedef boost::shared_ptr< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointArrayStamped_

typedef ::agv_msgs::WaypointArrayStamped_<std::allocator<void> > WaypointArrayStamped;

typedef boost::shared_ptr< ::agv_msgs::WaypointArrayStamped > WaypointArrayStampedPtr;
typedef boost::shared_ptr< ::agv_msgs::WaypointArrayStamped const> WaypointArrayStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'agv_msgs': ['/home/user/milrem/src/agv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "808c21c32e2c422f32f0484a3daade41";
  }

  static const char* value(const ::agv_msgs::WaypointArrayStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x808c21c32e2c422fULL;
  static const uint64_t static_value2 = 0x32f0484a3daade41ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/WaypointArrayStamped";
  }

  static const char* value(const ::agv_msgs::WaypointArrayStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"agv_msgs/Waypoint[] points\n"
"uint16 revision\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/Waypoint\n"
"float32 x\n"
"float32 y\n"
"float32 yaw\n"
"string goal_id\n"
"string frame_id\n"
"uint8 state\n"
;
  }

  static const char* value(const ::agv_msgs::WaypointArrayStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
      stream.next(m.revision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointArrayStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::WaypointArrayStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::WaypointArrayStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "revision: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.revision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_WAYPOINTARRAYSTAMPED_H
